### ISSUE TITLE
Issue with Survivalist when mining.

### ISSUE THREAD

**Issue by AndaleTheGreat** [Lunatrius/Stackie#9] opened 2016-12-06 03:10 UTC
When mining stone quickly there is a crash if Survivlaist and Stackie are installed. 
Thorough testing has shown that it does not occur if either of these is disabled.
Does not seem to work when just throwing the items on the ground. Only when mining.

Crash Report - http://pastebin.com/iQtBupY4
Curse Profile Export - https://drive.google.com/file/d/0B-zCPBgxfnQUNlM1R3Vwd1R5RXc/view?usp=drivesdk
Video of example - https://drive.google.com/file/d/0B-zCPBgxfnQUN2toRWNsdkhSOXM/view?usp=drivesdk

- Forge 10.19.0.2180

- Crafting Tweaks (by BlayTheNinth)
- Ender Compass (by MrIbby)
- Survivalist (by gigaherz)
- Just Enough Items (JEI) (by mezz)
- Sparks Hammers (by Bright_Spark)
- Chameleon (by jaquadro)
- Storage Drawers (by jaquadro)
- Iron Chests (by progwml6)
- ElecCore | Rendering Library (by Elec332)
- CraftingTable IV (by Elec332)
- FastLeafDecay (by Olafskii)
- JourneyMap (by techbrew)
- Simple Grinder (by Rumaruka)
- CXLibrary (by CubeX2)
- More Furnaces (by CubeX2)
- SimpleHarvest (by TehNut)
- LunatriusCore (by Lunatrius)
- Stackie (by Lunatrius)
- Food Expansion (by Lellson)
- Convenient Additions (by NecroticDEV)
- Tree Chopper (by DuchLord)
- OpenBlocks Elevator (by VsnGamer)
- TheDragonLib (by Moritz30)
- ArmorPlus (by Moritz30)
- Reap Mod (by EuhDawson)
- Flour Power (by Anteater46)
- Craftable Saddles (by 456Xander)
- Armor Recalc (by TheOldOne22)
- Level Up! (by BeetoGuy)

Crossposted to Survivalist bugs: https://github.com/gigaherz/Survivalist/issues/23

**Comment by Lunatrius** [comment] 2016-12-06 10:44
The crash happens because Stackie sets the `stackSize` to `0` and `isDead` to `true`.

This can be fixed in both mods, but I'll check if I can manually remove all dead entities from the list after the iteration.

**Comment by gigaherz** [comment] 2016-12-06 21:52
I really wonder how Survivalist's presence reveals this. The mod doesn't do anything with item entities or stacks, besides replacing certain drops...

**Comment by Lunatrius** [comment] 2016-12-07 18:34
I just noticed it, but yeah... it's actually Convenient Additions that's crashing because of the invalid stacks.

Can you run the game with only Stackie, Convenient Additions and any required dependencies? And check whether you can reproduce the crash? Survivalist seems irrelevant.

**Comment by AndaleTheGreat** [comment] 2016-12-11 04:02
I absolutely cannot seem to reproduce this without Survivalist and mining quickly thru stone.

**Comment by Lunatrius** [comment] 2016-12-11 10:43
```
java.lang.IllegalArgumentException: Stack can not be invalid!
    at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:437)
-------- v
    at convenientadditions.item.adventurersPickaxe.OreMagnet.isOreItem(OreMagnet.java:22)
    at convenientadditions.item.adventurersPickaxe.OreMagnet.attractOres(OreMagnet.java:15)
    at convenientadditions.item.adventurersPickaxe.ItemAdventurersPickaxe.onPlayerInventoryTick(ItemAdventurersPickaxe.java:331)
    at convenientadditions.item.PlayerInventoryTickHandler.onPlayerInventoryTick(PlayerInventoryTickHandler.java:22)
-------- ^
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_23_PlayerInventoryTickHandler_onPlayerInventoryTick_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:361)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:188)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:174)
    at net.minecraft.world.World.func_72866_a(World.java:1987)
    at net.minecraft.world.World.func_72870_g(World.java:1957)
    at net.minecraft.world.World.func_72939_s(World.java:1773)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1782)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1054)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Survivalist is no where in the stack trace, so unless it messes around with item stack entities (like Stackie does) there should be no way for the game to crash because of it.

Have you tried using only Survivalist and Convenient Additions to try to reproduce the crash?

**Comment by Necr0** [comment] 2016-12-11 13:03
Ok, great! I get it. I'll take care of it. The built in Ore Magnet of the Adventurer's Pickaxe isn't checking if the EntityItem's stack is still valid before trying to check it's Ore Dictionary entries. It's CA's fault. You can close this issue.

**Comment by AndaleTheGreat** [comment] 2016-12-11 14:45
Gotta say, pretty happy that one bug report has been seen by three very helpful authors that are very being super attentive to their work.

**Closed** 2016-12-12 01:46 UTC
Labels: bug
